spring:
  datasource:
    url: jdbc:phoenix:192.168.188.101,192.168.188.102,192.168.188.103:2181
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    type: com.alibaba.druid.pool.DruidDataSource
    #Spring不会配置连接池的具体配置
    initial-size: 5
    minIdle: 5
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

server:
  port: 8080





